// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gbctkgylkzcpswyeurmv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdiY3RrZ3lsa3pjcHN3eWV1cm12Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM0MTg4MTEsImV4cCI6MjA1ODk5NDgxMX0.zYBaSeSb-x16uSerKxroSzIwkaRnJif1Rd66gMg3X7M";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);